# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: >-
      ^docs/[^/]*\.svg$
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-executables-have-shebangs
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.8.0'
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 21.5b2 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
    - id: black
      language_version: python3 # Should be a command that runs python3.6+

- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.1
  hooks:
  - id: pyupgrade
    args: ['--py38-plus', '--keep-runtime-typing']

- repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  rev: v1.0.1
  hooks:
  - id: rst-linter
    files: >-
      ^[^/]+[.]rst$

- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: "^docs/"
    additional_dependencies: [flake8-typing-imports==1.7.0]

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.7
  hooks:
  -   id: autopep8

# - repo: https://github.com/asottile/reorder_python_imports
#   rev: v2.4.0
#   hooks:
#   - id: reorder-python-imports

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.812
#   hooks:
#   - id: mypy
#     args: [-v]
#     additional_dependencies: ['typing-extensions', 'mypy-extensions', 'mypy-boto3', 'boto3-stubs[ec2,ecs,lambda]', 'pytest']
#     exclude: "setup.py"

- repo: local
  hooks:
  - id: local-mypy
    name: Run mypy through venv
    language: system
    entry: make mypy
    pass_filenames: false
